In [57]:
from pandas import *

df_raw: DataFrame = read_excel("sampleCur.xlsx", skiprows=6, na_values=[' '])
# df_raw = df_raw.dropna()
df_raw = df_raw[to_numeric(df_raw['#'], errors='coerce').notnull()]
df_raw

,#,Number of Generations,Club Member (First name/Last name),Unnamed: 3,CNV (Cumulated Network Volume),Rank,P,PV (Personal Volume),PVG,MCR (Maximum Confirmed Rank),Number of months with zero Volume Points accrued,Club Member Status
0,1,.0,6111685.0,Галюк Елена,> 500,E,NaN,100.0,230.0,E/1,NaN,NaN
1,2,.1,6190205.0,Галюк Дмитрий,> 500,D,NaN,NaN,NaN,SD/28,1.0,m
2,3,.2,6202838.0,Tabolich Anastasiya,> 500,PM,NaN,NaN,NaN,NaN,12.0,m
3,4,.2,6866923.0,Фалавандишвили Натия,> 500,PM,NaN,NaN,7.0,D/28,7.0,m
4,5,.3,6959087.0,Мурванидзе Луиза,> 500,PM,NaN,7.0,NaN,NaN,NaN,m
...,...,...,...,...,...,...,...,...,...,...,...,...
723,724,.1,7625037.0,Зоидзе Светлана,273.4,NaN,NaN,NaN,NaN,NaN,4.0,m
724,725,.1,7634313.0,Rodionova Elena,69,NaN,NaN,NaN,NaN,NaN,2.0,m
725,726,.1,7659464.0,Каитамба Раули,82.2,M,NaN,NaN,NaN,NaN,1.0,m
726,727,.1,7742962.0,Павлова Ирина,500,PM,NaN,NaN,NaN,D/2,2.0,m
727,728,.1,7821743.0,Lohvynenko Olha,NaN,NaN,NaN,68.0,NaN,NaN,NaN,m

In [58]:
excel2Field = {}
excel2Field["#"] = "rownum"
excel2Field["Number of Generations"] = "gen"
excel2Field["Club Member (First name/Last name)"] = "Id"
excel2Field["Unnamed: 3"] = "Name"
excel2Field["CNV (Cumulated Network Volume)"] = "cnv"
excel2Field["Rank"] = "Rank"
excel2Field["P"] = "Pending"
excel2Field["PV (Personal Volume)"] = "Personal"
excel2Field["PVG"] = "Group"
excel2Field["MCR (Maximum Confirmed Rank)"] = "maxrank"
excel2Field["Number of months with zero Volume Points accrued"] = "zeroMonths"
excel2Field["Club Member Status"] = "status"

df_renamed = df_raw.rename(columns=excel2Field)
df_renamed

,rownum,gen,Id,Name,cnv,Rank,Pending,Personal,Group,maxrank,zeroMonths,status
0,1,.0,6111685.0,Галюк Елена,> 500,E,NaN,100.0,230.0,E/1,NaN,NaN
1,2,.1,6190205.0,Галюк Дмитрий,> 500,D,NaN,NaN,NaN,SD/28,1.0,m
2,3,.2,6202838.0,Tabolich Anastasiya,> 500,PM,NaN,NaN,NaN,NaN,12.0,m
3,4,.2,6866923.0,Фалавандишвили Натия,> 500,PM,NaN,NaN,7.0,D/28,7.0,m
4,5,.3,6959087.0,Мурванидзе Луиза,> 500,PM,NaN,7.0,NaN,NaN,NaN,m
...,...,...,...,...,...,...,...,...,...,...,...,...
723,724,.1,7625037.0,Зоидзе Светлана,273.4,NaN,NaN,NaN,NaN,NaN,4.0,m
724,725,.1,7634313.0,Rodionova Elena,69,NaN,NaN,NaN,NaN,NaN,2.0,m
725,726,.1,7659464.0,Каитамба Раули,82.2,M,NaN,NaN,NaN,NaN,1.0,m
726,727,.1,7742962.0,Павлова Ирина,500,PM,NaN,NaN,NaN,D/2,2.0,m
727,728,.1,7821743.0,Lohvynenko Olha,NaN,NaN,NaN,68.0,NaN,NaN,NaN,m

In [59]:
df_recast = df_renamed.convert_dtypes(convert_floating=True, convert_integer=True)
df_recast["Personal"].astype(float)
df_recast

,rownum,gen,Id,Name,cnv,Rank,Pending,Personal,Group,maxrank,zeroMonths,status
0,1,.0,6111685,Галюк Елена,> 500,E,<NA>,100.0,230.0,E/1,<NA>,<NA>
1,2,.1,6190205,Галюк Дмитрий,> 500,D,<NA>,<NA>,<NA>,SD/28,1,m
2,3,.2,6202838,Tabolich Anastasiya,> 500,PM,<NA>,<NA>,<NA>,<NA>,12,m
3,4,.2,6866923,Фалавандишвили Натия,> 500,PM,<NA>,<NA>,7.0,D/28,7,m
4,5,.3,6959087,Мурванидзе Луиза,> 500,PM,<NA>,7.0,<NA>,<NA>,<NA>,m
...,...,...,...,...,...,...,...,...,...,...,...,...
723,724,.1,7625037,Зоидзе Светлана,273.4,<NA>,<NA>,<NA>,<NA>,<NA>,4,m
724,725,.1,7634313,Rodionova Elena,69,<NA>,<NA>,<NA>,<NA>,<NA>,2,m
725,726,.1,7659464,Каитамба Раули,82.2,M,<NA>,<NA>,<NA>,<NA>,1,m
726,727,.1,7742962,Павлова Ирина,500,PM,<NA>,<NA>,<NA>,D/2,2,m
727,728,.1,7821743,Lohvynenko Olha,NaN,<NA>,<NA>,68.0,<NA>,<NA>,<NA>,m

In [60]:
df_gen = df_recast
df_gen.gen=df_gen.gen.apply(lambda x: int(str(x).split(".")[-1]) )
df_gen

,rownum,gen,Id,Name,cnv,Rank,Pending,Personal,Group,maxrank,zeroMonths,status
0,1,0,6111685,Галюк Елена,> 500,E,<NA>,100.0,230.0,E/1,<NA>,<NA>
1,2,1,6190205,Галюк Дмитрий,> 500,D,<NA>,<NA>,<NA>,SD/28,1,m
2,3,2,6202838,Tabolich Anastasiya,> 500,PM,<NA>,<NA>,<NA>,<NA>,12,m
3,4,2,6866923,Фалавандишвили Натия,> 500,PM,<NA>,<NA>,7.0,D/28,7,m
4,5,3,6959087,Мурванидзе Луиза,> 500,PM,<NA>,7.0,<NA>,<NA>,<NA>,m
...,...,...,...,...,...,...,...,...,...,...,...,...
723,724,1,7625037,Зоидзе Светлана,273.4,<NA>,<NA>,<NA>,<NA>,<NA>,4,m
724,725,1,7634313,Rodionova Elena,69,<NA>,<NA>,<NA>,<NA>,<NA>,2,m
725,726,1,7659464,Каитамба Раули,82.2,M,<NA>,<NA>,<NA>,<NA>,1,m
726,727,1,7742962,Павлова Ирина,500,PM,<NA>,<NA>,<NA>,D/2,2,m
727,728,1,7821743,Lohvynenko Olha,NaN,<NA>,<NA>,68.0,<NA>,<NA>,<NA>,m

In [61]:
levelId = {}
def id_gen_2_parent(id, gen) -> int:
    levelId[gen] = id
    return levelId[gen-1] if gen > 0 else -1

if "ParentId" not in df_gen.columns:
    df_gen.insert(loc=3, column="ParentId", value=df_gen.apply(lambda x: id_gen_2_parent(x.Id, x.gen), axis=1))
    df_gen.ParentId = df_gen.ParentId.astype(int)

df_gen
df_gen.dtypes

rownum                 Int64
gen                    int64
Id                     Int64
ParentId               int64
Name          string[python]
cnv                   object
Rank          string[python]
Pending              Float64
Personal             Float64
Group                Float64
maxrank       string[python]
zeroMonths             Int64
status        string[python]
dtype: object

In [62]:
members = {}
parents = {}

def calculate_overallstructure_total(id):
    member = members[id]
    member["Overall"] += member["Personal"] or 0
    if id in parents:
        children = [c for c in members.values() if c["ParentId"] == member["Id"]]
        for c in children:
            member["Overall"] += calculate_overallstructure_total(c["Id"])
    return member["Overall"]

df_gen["Overall"] = 0
d = df_gen.to_dict(orient="index")
members = {r["Id"] : r for r in d.values()}
parents = {r["ParentId"] : r["Id"] for r in d.values()}
calculate_overallstructure_total(parents[-1])
memberOverall = {x["Id"]: x["Overall"] for x in members.values()}
df_gen["Overall"] = df_gen["Id"].map(memberOverall)
df_gen.head(50)

,rownum,gen,Id,ParentId,Name,cnv,Rank,Pending,Personal,Group,maxrank,zeroMonths,status,Overall
0,1,0,6111685,-1,Галюк Елена,> 500,E,<NA>,100.0,230.0,E/1,<NA>,<NA>,12884.7
1,2,1,6190205,6111685,Галюк Дмитрий,> 500,D,<NA>,<NA>,<NA>,SD/28,1,m,7.0
2,3,2,6202838,6190205,Tabolich Anastasiya,> 500,PM,<NA>,<NA>,<NA>,<NA>,12,m,0.0
3,4,2,6866923,6190205,Фалавандишвили Натия,> 500,PM,<NA>,<NA>,7.0,D/28,7,m,7.0
4,5,3,6959087,6866923,Мурванидзе Луиза,> 500,PM,<NA>,7.0,<NA>,<NA>,<NA>,m,7.0
5,6,4,7309266,6959087,Murvanidze Violeta,135.5,<NA>,<NA>,<NA>,<NA>,<NA>,3,m,0.0
6,7,3,7575828,6866923,Фалавандишвили Тинатин Тимуровна,35,<NA>,<NA>,<NA>,<NA>,<NA>,7,m,0.0
7,8,2,7688719,6190205,Konidala Anna,> 500,PM,<NA>,<NA>,<NA>,D/4,1,m,0.0
8,9,2,7791032,6190205,Shaposhnikov Mikhail,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,2,c/60,0.0
9,10,2,7805120,6190205,Галюк Елена Николаевна,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,1,c/49,0.0
10,11,2,7834868,6190205,Malyshava Katsiaryna,29,M,<NA>,<NA>,<NA>,<NA>,1,m,0.0
11,12,1,6190820,6111685,Синица Тома,> 500,PM,<NA>,21.5,21.5,D/69,<NA>,m,21.5
12,13,1,6203900,6111685,Галюк Варя,> 500,A,<NA>,43.5,102.5,D/3,<NA>,<NA>,234.2
13,14,2,6556807,6203900,Шидловская Анджела Григорьевна,> 500,PM,<NA>,11.0,<NA>,<NA>,<NA>,m,59.0
14,15,3,6673758,6556807,Вабищевич Анна,> 500,PM,<NA>,<NA>,<NA>,<NA>,2,m,0.0
15,16,4,6684011,6673758,Дедович Тамара,438.5,<NA>,<NA>,<NA>,<NA>,<NA>,5,m,0.0
16,17,4,6782839,6673758,Вабищевич Владимир Петрович,221,M,<NA>,<NA>,<NA>,<NA>,1,m,0.0
17,18,4,6801396,6673758,Вабищевич Мирослав Владимирович,225.1,<NA>,<NA>,<NA>,<NA>,<NA>,7,m,0.0
18,19,4,6842229,6673758,Будник Светлана Александровна,271.4,<NA>,<NA>,<NA>,<NA>,<NA>,6,m,0.0
19,20,4,7254343,6673758,Федосенко Екатерина,133.5,<NA>,<NA>,<NA>,<NA>,<NA>,4,m,0.0
20,21,3,6679651,6556807,Нестер Христина,> 500,PM,<NA>,33.0,<NA>,<NA>,<NA>,m,33.0
21,22,3,6702054,6556807,Вечерова Наталья,99,<NA>,<NA>,9.0,<NA>,<NA>,<NA>,m,9.0
22,23,3,6702224,6556807,Нестер Яна,> 500,PM,<NA>,6.0,<NA>,<NA>,<NA>,m,6.0
23,24,2,7187692,6203900,Коровкина Александра Михайловна,464.5,<NA>,<NA>,<NA>,<NA>,<NA>,6,m,0.0
24,25,2,7310915,6203900,Фролова Евгения,> 500,PM,<NA>,19.2,131.7,D/6,<NA>,m,131.7
25,26,3,7322535,7310915,Мадатова Дина,69.8,<NA>,<NA>,<NA>,<NA>,<NA>,8,m,0.0
26,27,3,7338482,7310915,Фролова Мелисса,> 500,PM,<NA>,10.5,<NA>,<NA>,<NA>,m,57.5
27,28,4,7439339,7338482,Грищенко Елена,94,<NA>,<NA>,<NA>,<NA>,<NA>,8,m,0.0
28,29,4,7449946,7338482,Назарова Наталия,90,<NA>,<NA>,<NA>,<NA>,<NA>,10,m,0.0
29,30,4,7456980,7338482,Kosiakova Ekaterina,438.2,M,<NA>,<NA>,<NA>,<NA>,1,m,47.0
30,31,5,7843365,7456980,Шакирьянов Артур Рафикович,NaN,<NA>,<NA>,47.0,<NA>,<NA>,<NA>,m,47.0
31,32,3,7436554,7310915,Терехина Екатерина Максимовна,133,<NA>,<NA>,<NA>,<NA>,<NA>,11,m,0.0
32,33,4,7437494,7436554,Акудович Антонина Сергеевна,50,<NA>,<NA>,<NA>,<NA>,<NA>,11,m,0.0
33,34,4,7526797,7436554,Mikhailova Nadezhda,71,<NA>,<NA>,<NA>,<NA>,<NA>,8,m,0.0
34,35,3,7536391,7310915,Minjaeva Olesya,24,<NA>,<NA>,<NA>,<NA>,<NA>,8,m,0.0
35,36,3,7554677,7310915,Makeenkova Anna,65,<NA>,<NA>,<NA>,<NA>,<NA>,7,m,0.0
36,37,3,7577949,7310915,Astrouskaya Yuliya,168,<NA>,<NA>,<NA>,<NA>,<NA>,6,m,0.0
37,38,3,7596790,7310915,Frolov Dmitry,196.4,<NA>,<NA>,<NA>,<NA>,<NA>,6,m,0.0
38,39,3,7833492,7310915,Lyashkevich Sofiya,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,1,c/30,0.0
39,40,3,7864524,7310915,Rasulova Natia,NaN,<NA>,<NA>,55.0,<NA>,<NA>,<NA>,m,55.0
40,41,1,6204299,6111685,Галюк Надя,> 500,A,<NA>,<NA>,<NA>,D/5,1,<NA>,41.0
41,42,2,6217050,6204299,Шинкевич Валентина,> 500,PM,<NA>,<NA>,41.0,D/23,1,m,41.0
42,43,3,6218172,6217050,Шинкевич Андрей,> 500,PM,<NA>,41.0,<NA>,<NA>,<NA>,m,41.0
43,44,4,6315386,6218172,Михайлова Мария,> 500,PM,<NA>,<NA>,<NA>,<NA>,1,m,0.0
44,45,4,6316880,6218172,Шинкевич Яна,> 500,PM,<NA>,<NA>,<NA>,<NA>,6,m,0.0
45,46,4,7049806,6218172,Воронович Юлия Валерьевна,> 500,PM,<NA>,<NA>,<NA>,<NA>,1,m,0.0
46,47,2,6742267,6204299,Свирид Ирина Михайловна,362.8,<NA>,<NA>,<NA>,<NA>,<NA>,12,m,0.0
47,48,2,6827084,6204299,Станкевич Оксана,467.7,<NA>,<NA>,<NA>,<NA>,<NA>,12,m,0.0
48,49,1,6300800,6111685,Баризоне Ольга Алексеевна,> 500,DD,25.0,50.0,434.0,E/5,<NA>,<NA>,4947.3
49,50,2,6361665,6300800,Баризоне Серджо,> 500,PM,<NA>,<NA>,<NA>,D/15,2,m,715.8

In [63]:
df_gen.head(50)

,rownum,gen,Id,ParentId,Name,cnv,Rank,Pending,Personal,Group,maxrank,zeroMonths,status,Overall
0,1,0,6111685,-1,Галюк Елена,> 500,E,<NA>,100.0,230.0,E/1,<NA>,<NA>,12884.7
1,2,1,6190205,6111685,Галюк Дмитрий,> 500,D,<NA>,<NA>,<NA>,SD/28,1,m,7.0
2,3,2,6202838,6190205,Tabolich Anastasiya,> 500,PM,<NA>,<NA>,<NA>,<NA>,12,m,0.0
3,4,2,6866923,6190205,Фалавандишвили Натия,> 500,PM,<NA>,<NA>,7.0,D/28,7,m,7.0
4,5,3,6959087,6866923,Мурванидзе Луиза,> 500,PM,<NA>,7.0,<NA>,<NA>,<NA>,m,7.0
5,6,4,7309266,6959087,Murvanidze Violeta,135.5,<NA>,<NA>,<NA>,<NA>,<NA>,3,m,0.0
6,7,3,7575828,6866923,Фалавандишвили Тинатин Тимуровна,35,<NA>,<NA>,<NA>,<NA>,<NA>,7,m,0.0
7,8,2,7688719,6190205,Konidala Anna,> 500,PM,<NA>,<NA>,<NA>,D/4,1,m,0.0
8,9,2,7791032,6190205,Shaposhnikov Mikhail,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,2,c/60,0.0
9,10,2,7805120,6190205,Галюк Елена Николаевна,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,1,c/49,0.0
10,11,2,7834868,6190205,Malyshava Katsiaryna,29,M,<NA>,<NA>,<NA>,<NA>,1,m,0.0
11,12,1,6190820,6111685,Синица Тома,> 500,PM,<NA>,21.5,21.5,D/69,<NA>,m,21.5
12,13,1,6203900,6111685,Галюк Варя,> 500,A,<NA>,43.5,102.5,D/3,<NA>,<NA>,234.2
13,14,2,6556807,6203900,Шидловская Анджела Григорьевна,> 500,PM,<NA>,11.0,<NA>,<NA>,<NA>,m,59.0
14,15,3,6673758,6556807,Вабищевич Анна,> 500,PM,<NA>,<NA>,<NA>,<NA>,2,m,0.0
15,16,4,6684011,6673758,Дедович Тамара,438.5,<NA>,<NA>,<NA>,<NA>,<NA>,5,m,0.0
16,17,4,6782839,6673758,Вабищевич Владимир Петрович,221,M,<NA>,<NA>,<NA>,<NA>,1,m,0.0
17,18,4,6801396,6673758,Вабищевич Мирослав Владимирович,225.1,<NA>,<NA>,<NA>,<NA>,<NA>,7,m,0.0
18,19,4,6842229,6673758,Будник Светлана Александровна,271.4,<NA>,<NA>,<NA>,<NA>,<NA>,6,m,0.0
19,20,4,7254343,6673758,Федосенко Екатерина,133.5,<NA>,<NA>,<NA>,<NA>,<NA>,4,m,0.0
20,21,3,6679651,6556807,Нестер Христина,> 500,PM,<NA>,33.0,<NA>,<NA>,<NA>,m,33.0
21,22,3,6702054,6556807,Вечерова Наталья,99,<NA>,<NA>,9.0,<NA>,<NA>,<NA>,m,9.0
22,23,3,6702224,6556807,Нестер Яна,> 500,PM,<NA>,6.0,<NA>,<NA>,<NA>,m,6.0
23,24,2,7187692,6203900,Коровкина Александра Михайловна,464.5,<NA>,<NA>,<NA>,<NA>,<NA>,6,m,0.0
24,25,2,7310915,6203900,Фролова Евгения,> 500,PM,<NA>,19.2,131.7,D/6,<NA>,m,131.7
25,26,3,7322535,7310915,Мадатова Дина,69.8,<NA>,<NA>,<NA>,<NA>,<NA>,8,m,0.0
26,27,3,7338482,7310915,Фролова Мелисса,> 500,PM,<NA>,10.5,<NA>,<NA>,<NA>,m,57.5
27,28,4,7439339,7338482,Грищенко Елена,94,<NA>,<NA>,<NA>,<NA>,<NA>,8,m,0.0
28,29,4,7449946,7338482,Назарова Наталия,90,<NA>,<NA>,<NA>,<NA>,<NA>,10,m,0.0
29,30,4,7456980,7338482,Kosiakova Ekaterina,438.2,M,<NA>,<NA>,<NA>,<NA>,1,m,47.0
30,31,5,7843365,7456980,Шакирьянов Артур Рафикович,NaN,<NA>,<NA>,47.0,<NA>,<NA>,<NA>,m,47.0
31,32,3,7436554,7310915,Терехина Екатерина Максимовна,133,<NA>,<NA>,<NA>,<NA>,<NA>,11,m,0.0
32,33,4,7437494,7436554,Акудович Антонина Сергеевна,50,<NA>,<NA>,<NA>,<NA>,<NA>,11,m,0.0
33,34,4,7526797,7436554,Mikhailova Nadezhda,71,<NA>,<NA>,<NA>,<NA>,<NA>,8,m,0.0
34,35,3,7536391,7310915,Minjaeva Olesya,24,<NA>,<NA>,<NA>,<NA>,<NA>,8,m,0.0
35,36,3,7554677,7310915,Makeenkova Anna,65,<NA>,<NA>,<NA>,<NA>,<NA>,7,m,0.0
36,37,3,7577949,7310915,Astrouskaya Yuliya,168,<NA>,<NA>,<NA>,<NA>,<NA>,6,m,0.0
37,38,3,7596790,7310915,Frolov Dmitry,196.4,<NA>,<NA>,<NA>,<NA>,<NA>,6,m,0.0
38,39,3,7833492,7310915,Lyashkevich Sofiya,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,1,c/30,0.0
39,40,3,7864524,7310915,Rasulova Natia,NaN,<NA>,<NA>,55.0,<NA>,<NA>,<NA>,m,55.0
40,41,1,6204299,6111685,Галюк Надя,> 500,A,<NA>,<NA>,<NA>,D/5,1,<NA>,41.0
41,42,2,6217050,6204299,Шинкевич Валентина,> 500,PM,<NA>,<NA>,41.0,D/23,1,m,41.0
42,43,3,6218172,6217050,Шинкевич Андрей,> 500,PM,<NA>,41.0,<NA>,<NA>,<NA>,m,41.0
43,44,4,6315386,6218172,Михайлова Мария,> 500,PM,<NA>,<NA>,<NA>,<NA>,1,m,0.0
44,45,4,6316880,6218172,Шинкевич Яна,> 500,PM,<NA>,<NA>,<NA>,<NA>,6,m,0.0
45,46,4,7049806,6218172,Воронович Юлия Валерьевна,> 500,PM,<NA>,<NA>,<NA>,<NA>,1,m,0.0
46,47,2,6742267,6204299,Свирид Ирина Михайловна,362.8,<NA>,<NA>,<NA>,<NA>,<NA>,12,m,0.0
47,48,2,6827084,6204299,Станкевич Оксана,467.7,<NA>,<NA>,<NA>,<NA>,<NA>,12,m,0.0
48,49,1,6300800,6111685,Баризоне Ольга Алексеевна,> 500,DD,25.0,50.0,434.0,E/5,<NA>,<NA>,4947.3
49,50,2,6361665,6300800,Баризоне Серджо,> 500,PM,<NA>,<NA>,<NA>,D/15,2,m,715.8